<a href="https://colab.research.google.com/github/beafshar/Active-Learning-Baselines/blob/main/Active_Learning_BL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd drive/
%ls

/content/drive
MyDrive/

In [3]:

%cd My Drive/AML Project/Credit Card Data
%ls

/content/drive/My Drive/AML Project/Credit Card Data
'Active Learning BL.ipynb'
 credit_card_transactions-ibm_v2.csv.zip
 sd254_cards.csv
 sd254_users.csv
 User0_credit_card_transactions.csv.zip

In [4]:
import pandas as pd

In [ ]:
data_v2 = pd.read_csv("credit_card_transactions-ibm_v2.csv.zip")
data_v2

In [5]:
data_read = pd.read_csv("User0_credit_card_transactions.csv.zip")
data = data_read
data

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19958,0,4,2009,2,12,13:03,$9.71,Swipe Transaction,4060646732831064559,La Verne,CA,91750.0,5411,Technical Glitch,No
19959,0,4,2009,2,22,11:58,$27.94,Swipe Transaction,-8129520121141002186,La Verne,CA,91750.0,5211,NaN,No
19960,0,4,2009,2,24,16:53,$13.97,Swipe Transaction,5474320255037684877,Hawthorne,CA,90250.0,5912,NaN,No
19961,0,4,2009,3,29,16:30,$14.27,Swipe Transaction,4060646732831064559,La Verne,CA,91750.0,5411,NaN,No
19962,0,4,2009,3,31,13:17,$13.55,Swipe Transaction,-4927381308738947637,Beijing,China,NaN,5812,NaN,No

#Splitting Train, Test and Pool data

In [6]:
import numpy as np
from sklearn.model_selection import train_test_split


train_ratio = 0.2
pool_ratio = 0.6
test_ratio = 1 - train_ratio - pool_ratio



labels = data["Is Fraud?"]
data = data.drop("Is Fraud?", axis=1)


# First split: 60% for training, 40% for remaining data
data_train, data_remaining, labels_train, labels_remaining = train_test_split(data, labels, test_size=(1 - train_ratio), random_state=42)

# Second split
data_pool, data_test, labels_pool, labels_test = train_test_split(data_remaining, labels_remaining, test_size=0.375, random_state=42)

# Now, data_train, labels_train contain 20% of the data
# data_pool, labels_pool contain 50% of the data
# data_test, labels_test contain 30% of the data

In [7]:
data_train["Is Fraud?"] = labels_train
data_train

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
11413,0,3,2004,8,6,21:45,$14.08,Swipe Transaction,-3265671264153192329,Monterey Park,CA,91754.0,7832,NaN,No
3882,0,0,2014,12,8,06:21,$132.34,Swipe Transaction,4060646732831064559,La Verne,CA,91750.0,5411,NaN,No
6055,0,1,2019,5,29,06:47,$36.63,Chip Transaction,4060646732831064559,La Verne,CA,91750.0,5411,NaN,No
11115,0,3,2004,1,21,06:57,$44.68,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
8135,0,2,2010,1,3,06:23,$143.63,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0,3,2004,5,25,00:15,$30.50,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
11964,0,3,2005,8,11,13:19,$11.67,Swipe Transaction,4060646732831064559,La Verne,CA,91750.0,5411,NaN,No
5390,0,1,2016,2,23,06:09,$148.96,Chip Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
860,0,0,2004,5,31,13:21,$10.43,Swipe Transaction,2027553650310142703,Mira Loma,CA,91752.0,5541,NaN,No
15795,0,3,2012,9,17,06:28,$115.60,Swipe Transaction,2027553650310142703,Mira Loma,CA,91752.0,5541,NaN,No

In [8]:
data_pool["Is Fraud?"] = labels_pool
data_pool

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
3195,0,0,2012,6,5,06:52,$39.65,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
9943,0,2,2017,3,2,06:46,$40.62,Chip Transaction,-34551508091458520,La Verne,CA,91750.0,5912,NaN,No
10803,0,3,2003,6,24,06:22,$157.43,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
9688,0,2,2015,10,2,17:45,$-212.00,Swipe Transaction,483490033258680568,Saint Louis,MO,63106.0,3504,NaN,No
15995,0,3,2013,2,7,21:31,$170.97,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18989,0,3,2018,6,5,09:43,$42.70,Swipe Transaction,-3345936507911876459,La Verne,CA,91750.0,7538,NaN,No
17919,0,3,2016,6,20,22:23,$165.77,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No
9300,0,2,2013,12,23,06:35,$36.57,Swipe Transaction,4060646732831064559,La Verne,CA,91750.0,5411,NaN,No
844,0,0,2004,5,21,06:03,$152.99,Swipe Transaction,6042526206085641250,Oceanside,CA,92051.0,5912,NaN,No
7901,0,2,2009,2,27,06:57,$-384.00,Swipe Transaction,-7807051024009846392,Bellflower,CA,90706.0,3684,NaN,No

In [9]:
data_test["Is Fraud?"] = labels_test
data_test

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
873,0,0,2004,6,23,06:27,$145.98,Swipe Transaction,1913477460590765860,La Verne,CA,91750.0,5300,NaN,No
3468,0,0,2013,4,23,09:56,$107.05,Online Transaction,-9092677072201095172,ONLINE,NaN,NaN,4900,NaN,No
5975,0,1,2019,1,6,13:07,$10.97,Chip Transaction,-2744911404133435018,North Grafton,MA,1536.0,5812,NaN,No
1419,0,0,2006,4,20,07:38,$58.29,Swipe Transaction,-3123328722007252436,Simi Valley,CA,93063.0,5193,NaN,No
18010,0,3,2016,9,3,07:06,$123.24,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11800,0,3,2005,5,12,20:23,$87.48,Swipe Transaction,-5023497618971072366,West Jordan,UT,84084.0,5812,NaN,No
3124,0,0,2012,3,17,13:18,$14.46,Swipe Transaction,2027553650310142703,Mira Loma,CA,91752.0,5541,NaN,No
2598,0,0,2010,6,23,07:28,$45.73,Swipe Transaction,-34551508091458520,La Verne,CA,91750.0,5912,NaN,No
7068,0,2,2006,5,29,06:18,$122.82,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
14507,0,3,2010,4,21,13:02,$6.25,Swipe Transaction,2027553650310142703,Mira Loma,CA,91752.0,5541,NaN,No

Handling Missing Values

In [10]:
from sklearn.preprocessing import LabelEncoder

class preprocessor(object):
  def __init__(self, df):
    self.df = df
  def handle_missing_values(self):
    nan_cols = ["Merchant State","Zip"]
    self.df = self.df.drop("Errors?", axis = 1)
    self.df[nan_cols] = self.df[nan_cols].fillna(self.df[nan_cols].mode().iloc[0])

  def handle_amount(self):
    self.df['Amount'] = pd.to_numeric(self.df['Amount'].str.replace('$', ''), errors='coerce')

  def handle_label(self):
    le = LabelEncoder()
    self.df['Is Fraud?'] = le.fit_transform(self.df['Is Fraud?'])

  def handle_time(self):
    self.df['Hours'] = self.df['Time'].str.split(':').str[0].astype(int)
    self.df['Minutes'] = self.df['Time'].str.split(':').str[1].astype(int)
    self.df['Total_minutes'] = self.df['Hours'] * 60 + self.df['Minutes']
    self.df = self.df.drop("Time", axis = 1)
    self.df = self.df.drop("Hours", axis = 1)
    self.df = self.df.drop("Minutes", axis = 1)

  def handle_categorical(self):
    categorical_columns = self.df.select_dtypes(include=['object']).columns.tolist()
    le = LabelEncoder()

    for col in categorical_columns:
        self.df[col + '_encoded'] = le.fit_transform(self.df[col])

    self.df = self.df.drop(categorical_columns, axis=1)
  def run(self):
    self.handle_missing_values()
    self.handle_amount()
    self.handle_label()
    self.handle_time()
    self.handle_categorical()
    print(self.df.info())
    print("--------------------------")
    return self.df

In [11]:
train_preprocessor = preprocessor(data_train)
data_train = train_preprocessor.run()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3992 entries, 11413 to 15795
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User                    3992 non-null   int64
 1   Card                    3992 non-null   int64
 2   Year                    3992 non-null   int64
 3   Month                   3992 non-null   int64
 4   Day                     3992 non-null   int64
 5   Amount                  3992 non-null   float64
 6   Merchant Name           3992 non-null   int64
 7   Zip                     3992 non-null   float64
 8   MCC                     3992 non-null   int64
 9   Is Fraud?               3992 non-null   int64
 10  Total_minutes           3992 non-null   int64
 11  Use Chip_encoded        3992 non-null   int64
 12  Merchant City_encoded   3992 non-null   int64
 13  Merchant State_encoded  3992 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 467.8 KB
None
--------------------------

<ipython-input-10-1b9d6f365e6e>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  self.df['Amount'] = pd.to_numeric(self.df['Amount'].str.replace('$', ''), errors='coerce')

In [12]:
pool_preprocessor = preprocessor(data_pool)
data_pool = pool_preprocessor.run()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9981 entries, 3195 to 7901
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User                    9981 non-null   int64
 1   Card                    9981 non-null   int64
 2   Year                    9981 non-null   int64
 3   Month                   9981 non-null   int64
 4   Day                     9981 non-null   int64
 5   Amount                  9981 non-null   float64
 6   Merchant Name           9981 non-null   int64
 7   Zip                     9981 non-null   float64
 8   MCC                     9981 non-null   int64
 9   Is Fraud?               9981 non-null   int64
 10  Total_minutes           9981 non-null   int64
 11  Use Chip_encoded        9981 non-null   int64
 12  Merchant City_encoded   9981 non-null   int64
 13  Merchant State_encoded  9981 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 1.1 MB
None
--------------------------

<ipython-input-10-1b9d6f365e6e>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  self.df['Amount'] = pd.to_numeric(self.df['Amount'].str.replace('$', ''), errors='coerce')

In [13]:
test_preprocessor = preprocessor(data_test)
data_test = test_preprocessor.run()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5990 entries, 873 to 14507
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User                    5990 non-null   int64
 1   Card                    5990 non-null   int64
 2   Year                    5990 non-null   int64
 3   Month                   5990 non-null   int64
 4   Day                     5990 non-null   int64
 5   Amount                  5990 non-null   float64
 6   Merchant Name           5990 non-null   int64
 7   Zip                     5990 non-null   float64
 8   MCC                     5990 non-null   int64
 9   Is Fraud?               5990 non-null   int64
 10  Total_minutes           5990 non-null   int64
 11  Use Chip_encoded        5990 non-null   int64
 12  Merchant City_encoded   5990 non-null   int64
 13  Merchant State_encoded  5990 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 702.0 KB
None
--------------------------

<ipython-input-10-1b9d6f365e6e>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  self.df['Amount'] = pd.to_numeric(self.df['Amount'].str.replace('$', ''), errors='coerce')

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [15]:
y_train = data_train["Is Fraud?"]
X_train = data_train.drop("Is Fraud?", axis=1)

y_test = data_test["Is Fraud?"]
X_test = data_test.drop("Is Fraud?", axis=1)


rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)


rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)
print(f'f1_score: {f1* 100}%')

Accuracy: 99.83%
f1_score: 0.0%

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification
from sklearn.utils import shuffle
import numpy as np


class ActiveLearner(object):
  def __init__(self, model,X_initial,y_initial, X_pool, y_pool, X_test, y_test):
    self.model = model
    self.X_initial = X_initial
    self.y_initial = y_initial
    self.X_pool = X_pool
    self.y_pool = y_pool
    self.X_test = X_test
    self.y_test = y_test

  def learn(self, method = "UNC_SAMPLE", n_queries=10):
      for i in range(n_queries):
        y_proba = rf_classifier.predict_proba(X_pool)
        # Calculate uncertainty scores using entropy
        uncertainty_scores = -np.sum(y_proba * np.log2(y_proba), axis=1)
        # Select the most uncertain samples
        query_indices = uncertainty_scores.argsort()[:n_queries]
        # Get the selected samples
        query_samples = X_pool[query_indices]
        query_labels = y_pool[query_indices]
        # Add these samples to the training set
        X_train = np.vstack((X_initial, query_samples))
        y_train = np.hstack((y_initial, query_labels))
        # Remove these samples from the pool set
        X_pool = np.delete(X_pool, query_indices, axis=0)
        y_pool = np.delete(y_pool, query_indices)
        # Retrain the model
        rf_classifier.fit(X_train, y_train)
        # Update initial training set
        X_initial, y_initial = X_train, y_train
      return self.model

  def uncertainity_sampling(self):
    pass

  def query_by_committee(self):
    pass

  def expected_model_change(self):
    pass

  def variance_reduction(self):
    pass

  def MSE_reduction(self):
    pass

  def density_weighting(self):
    pass


def active_learning(rf_classifier,X_initial,y_initial, X_pool, y_pool, n_queries=10, n_estimates = 10):
    for i in range(n_queries):

        y_proba = rf_classifier.predict_proba(X_pool)

        tempdf = pd.DataFrame(y_proba, columns=["A", "B"])
        tempdf["index"] = X_pool.index
        print(tempdf)


        tempdf["score"] = -np.abs(tempdf["A"] - tempdf["B"])
        print("-------------")
        print(tempdf)
        sorted_df = tempdf.sort_values(by='score')[:n_estimates]
        print("-------------")
        print(sorted_df["score"].unique())
        # query_indices = uncertainty_scores.argsort()[:n_queries]
        query_indices = sorted_df.index


        print(query_indices)




        X_train = np.vstack((X_initial, X_pool.iloc[query_indices]))
        y_train = np.hstack((y_initial, y_pool.iloc[query_indices]))


        # x_pool = X_pool.drop(query_indices, axis=0)
        X_pool = np.delete(X_pool, query_indices, axis= 0)
        y_pool = np.delete(y_pool, query_indices)


        rf_classifier.fit(X_train, y_train)

        X_initial, y_initial = X_train, y_train

    return rf_classifier


y_pool = data_pool["Is Fraud?"]
X_pool = data_pool.drop("Is Fraud?", axis=1)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

updated_rf_classifier = active_learning(rf_classifier,X_train,y_train, X_pool, y_pool, n_queries=10)

y_pred = updated_rf_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy after active learning: {accuracy * 100:.2f}%')

        A    B  index
0     1.0  0.0   3195
1     1.0  0.0   9943
2     1.0  0.0  10803
3     1.0  0.0   9688
4     1.0  0.0  15995
...   ...  ...    ...
9976  1.0  0.0  18989
9977  1.0  0.0  17919
9978  1.0  0.0   9300
9979  1.0  0.0    844
9980  1.0  0.0   7901

[9981 rows x 3 columns]
-------------
        A    B  index  score
0     1.0  0.0   3195   -1.0
1     1.0  0.0   9943   -1.0
2     1.0  0.0  10803   -1.0
3     1.0  0.0   9688   -1.0
4     1.0  0.0  15995   -1.0
...   ...  ...    ...    ...
9976  1.0  0.0  18989   -1.0
9977  1.0  0.0  17919   -1.0
9978  1.0  0.0   9300   -1.0
9979  1.0  0.0    844   -1.0
9980  1.0  0.0   7901   -1.0

[9981 rows x 4 columns]
-------------
[-1.]
Int64Index([0, 6494, 6495, 6496, 6497, 6498, 6499, 6493, 6500, 6502], dtype='int64')

ValueError: ignored